baseurl = "https://adamtervort.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Adam Tervort"
subtitle = "I work on the people side of an awesome tech company. I â¤ï¸KC, âš¾ï¸Royals, jazzğŸ¶, hammocks, ä¸­æ–‡, ğŸ‡¹ğŸ‡¼, microgreens ğŸŒ±."
theme = "stip"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Adam Tervort"
    bio = "Customer Success, Marketing, and Analog Productivity"
    # bio = "I â¤ï¸KC, âš¾ï¸Royals, jazzğŸ¶, hammocks, ä¸­æ–‡, ğŸ‡¹ğŸ‡¼, microgreens ğŸŒ±"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "rss"
        title = "Read more on Hammock Marketing, my blog ğŸ“"
        url = "https://hammock.marketing"      
    
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "Prefer email? I can do that ğŸ“¨"
        url = "mailto:adam@adamtervort.com"
 
    [[params.links]]
        icon = "twitter"
        title = "Connect with me on Twitter ğŸ¦"
        url = "https://twitter.com/adamtervort/"

    [[params.links]]
        icon = "github"
        title = "Projects on Github ğŸ™"
        url = "https://github.com/adamprime"


      
